### ISSUE TITLE
cannot run the project, having error

### ISSUE THREAD

**Issue by Siberiabear99** [jasonwebb/2d-diffusion-limited-aggregation-experiments#3]
i used the following sequence"
npm install
cd core
npm install
cd ..
npm run serve
"
and got
"
cjj@yxy-MS-7D46:~/cjj_project/2d-diffusion-limited-aggregation-experiments$ npm run serve

> 2d-diffusion-limited-aggregation-experiments@1.0.0 serve
> webpack-dev-server

/home/cjj/cjj_project/2d-diffusion-limited-aggregation-experiments/node_modules/webpack-cli/bin/utils/prompt-command.js:46
        return func(...args);
               ^

TypeError: Class constructor ServeCommand cannot be invoked without 'new'
    at runWhenInstalled (/home/cjj/cjj_project/2d-diffusion-limited-aggregation-experiments/node_modules/webpack-cli/bin/utils/prompt-command.js:46:9)
    at promptForInstallation (/home/cjj/cjj_project/2d-diffusion-limited-aggregation-experiments/node_modules/webpack-cli/bin/utils/prompt-command.js:140:10)
    at /home/cjj/cjj_project/2d-diffusion-limited-aggregation-experiments/node_modules/webpack-cli/bin/cli.js:32:43
    at Object.<anonymous> (/home/cjj/cjj_project/2d-diffusion-limited-aggregation-experiments/node_modules/webpack-cli/bin/cli.js:366:3)
    at Module._compile (node:internal/modules/cjs/loader:1257:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1311:10)
    at Module.load (node:internal/modules/cjs/loader:1115:32)
    at Module._load (node:internal/modules/cjs/loader:962:12)
    at Module.require (node:internal/modules/cjs/loader:1139:19)
    at require (node:internal/modules/helpers:121:18)

Node.js v20.3.1
"

**Comment by jasonwebb** [comment]
Fixed! Updated [instructions are in the README](https://github.com/jasonwebb/2d-diffusion-limited-aggregation-experiments?tab=readme-ov-file#running-locally), but the gist is you'll want to be on Node v16, then reinstall the packages the same way.
